name = "wowtag-backend"
main = "src/index.ts"
compatibility_date = "2024-03-25"

# [vars]
# FRONTEND_URL = "https://wowtag.pages.dev"

# [[d1_databases]]
# binding = "DB"
# database_name = "wowtag-db"
# database_id = "your-d1-id-here"

# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "wowtag-contents"
