#:schema node_modules/wrangler/config-schema.json
name = "wowtag"
compatibility_date = "2026-03-25"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB" # Hono에서 c.env.DB로 접근할 이름
database_name = "wowtag-db"
database_id = "39f78334-6415-4a81-87f8-2e9ee0546626"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "wowtag-contents"

